# Generated by Django 3.2.6 on 2021-08-21 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoFinal', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='usuario',
            table='usuarios',
        ),
    ]
