# Generated by Django 3.2.6 on 2021-08-21 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoFinal', '0002_alter_usuario_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='correo',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='es_admin',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='ult_acceso',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
