# Generated by Django 3.2.6 on 2021-08-23 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_auto_20210823_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='puntos',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
