# Generated by Django 3.2.6 on 2021-08-26 17:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_auto_20210823_2106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='es_admin',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='nickname',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='ult_acceso',
        ),
        migrations.CreateModel(
            name='Partida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntos', models.IntegerField()),
                ('cnt_respondidas', models.IntegerField()),
                ('fecha', models.DateField()),
                ('idusuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'partida',
            },
        ),
    ]
