# Generated by Django 3.2.6 on 2021-08-26 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_auto_20210826_1404'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='ult_acceso',
        ),
    ]
