# Generated by Django 3.2.6 on 2021-08-26 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_remove_usuario_ult_acceso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='es_admin',
        ),
    ]
