# Generated by Django 3.2.6 on 2021-08-26 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0009_usuario_is_valid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='is_valid',
            field=models.BooleanField(blank=True, max_length=255, null=True),
        ),
    ]
