# Generated by Django 3.2.6 on 2021-08-29 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Partida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('puntos', models.IntegerField()),
            ],
            options={
                'db_table': 'Partida',
            },
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto_pregunta', models.CharField(max_length=255)),
                ('respuesta_correcta', models.CharField(max_length=255)),
                ('respuesta_incorrecta_1', models.CharField(max_length=255)),
                ('respuesta_incorrecta_2', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Pregunta',
            },
        ),
    ]
