# Generated by Django 3.2.6 on 2021-08-25 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preguntas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pregunta',
            name='categoria',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
