# Generated by Django 3.2.6 on 2021-08-25 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preguntas', '0002_pregunta_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pregunta',
            name='categoria',
            field=models.CharField(blank=True, choices=[('CULTURA Y ARTE', 'Cultura y Arte'), ('HISTORIA', 'Historia'), ('DEPORTE', 'Deporte'), ('GEOGRAFIA', 'Geografia'), ('ECONOMIA', 'Economia'), ('CIENCIA Y EDUCACION', 'Ciencia y Educacion'), ('ENTRETENIMIENTO', 'Entretenimieto')], max_length=255, null=True),
        ),
    ]
