# Generated by Django 3.2.6 on 2021-08-25 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('preguntas', '0003_alter_pregunta_categoria'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='pregunta',
            table='Pregunta',
        ),
        migrations.AlterModelTable(
            name='respuesta',
            table='Respueta',
        ),
    ]
