# Generated by Django 3.2.6 on 2021-08-29 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('preguntas', '0003_alter_partida_fecha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pregunta',
            name='respuesta_correcta',
        ),
        migrations.RemoveField(
            model_name='pregunta',
            name='respuesta_incorrecta_1',
        ),
        migrations.RemoveField(
            model_name='pregunta',
            name='respuesta_incorrecta_2',
        ),
        migrations.AddField(
            model_name='pregunta',
            name='nivel',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Respuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto_respuesta', models.CharField(max_length=255)),
                ('es_correcta', models.BooleanField(default=False)),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='preguntas.pregunta')),
            ],
            options={
                'db_table': 'Respuesta',
            },
        ),
    ]
