# Generated by Django 3.2.6 on 2021-08-25 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preguntas', '0004_auto_20210825_1047'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('puntos', models.IntegerField()),
                ('cnt_respondidas', models.IntegerField()),
                ('preguntas', models.ManyToManyField(related_name='preguntas', to='preguntas.Pregunta')),
            ],
            options={
                'db_table': 'Partida',
            },
        ),
        migrations.AddField(
            model_name='pregunta',
            name='id_partida',
            field=models.ManyToManyField(to='preguntas.Partida'),
        ),
    ]
