# Generated by Django 3.2.6 on 2021-08-21 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Partida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntos', models.IntegerField()),
                ('cnt_respondidas', models.IntegerField()),
                ('fecha', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_partida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Juego.partida')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('nickname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('es_admin', models.BooleanField()),
                ('puntaje', models.IntegerField()),
                ('ult_acceso', models.DateField()),
                ('partidas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Juego.partida')),
            ],
        ),
        migrations.CreateModel(
            name='Respuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('es_correcta', models.BooleanField()),
                ('id_pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Juego.pregunta')),
            ],
        ),
        migrations.AddField(
            model_name='pregunta',
            name='respuestas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Juego.respuesta'),
        ),
        migrations.AddField(
            model_name='partida',
            name='idusuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Juego.usuario'),
        ),
        migrations.AddField(
            model_name='partida',
            name='preguntas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Juego.pregunta'),
        ),
    ]
